# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
  - cron: "30 1 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: run script
        run: powershell -ExecutionPolicy Bypass -C "$env:GITHUB_WORKSPACE/arcwin10-1.2.4.ps1"
        shell: pwsh
        
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Arc.zip
          tag_name: ${{ steps.bump.outputs.new_tag }}
